# Generated by Django 5.0.7 on 2024-07-23 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_todo_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_code',
            field=models.CharField(choices=[('MO', '월요일'), ('TU', '화요일'), ('WE', '수요일'), ('TH', '목요일'), ('FR', '금요일'), ('SA', '토요일'), ('SU', '일요일')], max_length=2, unique=True),
        ),
    ]
